### ISSUE TITLE
Hi, GitHub's recommended brought me here

### ISSUE THREAD

**Issue by 12345ieee** [shiawasenahikari/SHENZHEN-IO-Solutions#1]
And for one time, it made sense.

I maintain the "official" leaderboard at https://www.reddit.com/r/shenzhenIO/wiki/index and https://github.com/12345ieee/shenzhenIO-leaderboard and you have a lot of nice stuff here, including a CP record.

I won't just straight out throw your stuff in the leaderboard without permission, but consider taking a look.

**Comment by shiawasenahikari** [comment]
I know that leader board, and I did post a top power solution of 3113 in September. The author HikariToyama is me.

Am I holding another top solution but I don't realise?
